title: UML .FRI 2
description: UML .FRI is nice CASE tool with DSM capabilities
email: jan.janech@kst.uniza.sk
author: Jan Janech
exclude:
  - assets/images/screenshots/convert.sh
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "assets/**"
    values:
      sitemap:         false
